package com.algokelvin.openfile;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.util.Base64;
import android.widget.Toast;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.FileProvider;

import com.algokelvin.openfile.databinding.ActivityMainBinding;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class MainActivity extends AppCompatActivity {
    private final int REQUEST_OPEN_EXCEL = 5000;
    private final int REQUEST_OPEN_DOC = 6000;
    private final int REQUEST_OPEN_PPT = 7000;
    private ActivityMainBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());
        initialize(binding);
    }

    private void initialize(ActivityMainBinding binding) {
        binding.btnOpenDoc.setOnClickListener(v -> viewFileDoc());
        binding.btnOpenExcel.setOnClickListener(v -> viewFileExcel());
        binding.btnOpenPpt.setOnClickListener(v -> viewFilePpt());
    }

    private void viewFileDoc() {

    }

    private void viewFileExcel() {
        File file = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).getPath() + "/algokelvinexcel");
        if (!file.exists()) {
            file.mkdirs();
        }

        int noFile = 4356322;
        String fileName = "Sample_File_Excel";
        String base64Excel = "UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRfdI/EPkLUrcskAINe2CxxIqUT7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaCiMa7UgyLgcjAVV4bNy/Fx+wlvxcZknJaWe+gFBtAMRlfX41mmwCYcbfDUjRE4UFKrBpoFRY+gOOd2sdWEd/GuQyqWqg5yNvB4E5W3hE4yqnTEOPRE9RqaSl7XvPjLUkEiyJ73BZ2XqVQIVhTKWJSuXL6l0u+cyi4M9VgYwLeMIaQvQ7dzt8Gu743Hk00GrKpivSqWsaQayu/fFx8er8ojov0UPq6NhVoXy1bnkCBIYLS2ABQa4u0Fq0ybs99xD8Vo0zL8MIg3fsl4RMcxN8bZLqej5BkThgibSzgpceeRE85NyqCfqfIybg4wE/tYxx8bqbRB+QERfj/FPYR6brzwEIQycAhJH2H7eDI6Tt77NDlW4Pu8ZbpfzL+BgAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVBqDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6pPPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAAgAAAAhAObwxc7eAgAAtwYAAA8AAAB4bC93b3JrYm9vay54bWysVU1vozAQva+0/wH5TsFAIEGlVVISbbTtKmq77aVS5YATrABmbedLVf/7jiEkTXPptovAgxl4fjPzPJxfborcWFEhGS8jhM9sZNAy4Skr5xH6fT8yu8iQipQpyXlJI7SlEl1efP92vuZiMeV8YQBAKSOUKVWFliWTjBZEnvGKluCZcVEQBVMxt2QlKEllRqkqcsuxbd8qCCtRgxCKj2Dw2YwlNObJsqClakAEzYkC+jJjlWzRiuQjcAURi2VlJryoAGLKcqa2NSgyiiQcz0suyDSHsDe4Y2wEnD5c2IbBaVcC18lSBUsEl3ymzgDaakifxI9tC+OjFGxOc/AxJM8SdMV0DfeshP9JVv4eyz+AYfvLaBikVWslhOR9Eq2z5+agi/MZy+lDI12DVNUvUuhK5cjIiVTDlCmaRiiAKV/TwwOISiyrwZLl4HWCrmsj62Iv54mACdS+nysqSqLoFS8VSG1H/auyqrGvMg4iNm7pnyUTFPYOSAjCgZEkIZnKCVGZsRR5hOLwqZ/P+U+ar1j5dLN9vqWSEpFkT2/UR06l/g/6I4kO34KQG1rN/fvwgZ0IW41NlDDgfhxfQ57vyAqyDrVNd5tyDGnF7nOZiBA/vwTDUbeH7a6J4wE2PRwMzX7su6bt9kYDJw7sYBC8QjDCDxNOlirbFVRDR8iD6p24bsim9WA7XLL0QOPF3h2mtu+G1veqA9at64HRtTyUXk+NzSMrU76OkAmkkbE9nq5r5yNLVQbacZ0OiKl59oOyeQaMsdvt6X0jHM0sQkeM4obRCA5TD0eMrDeU6iYJ1GprlLWw73TjxNCNta2TDEIO9RpinOK6iO1nCcmTiTC0qV/0nR529Rt0o66lqi0IjAE97Nn9wO55pj10O6bX7Tlm13Md88qLnWEnGMbDQUfXRzf58H+0ulrnYfv30CwzItS9IMkC/jm3dDYgEgTVBAR8QY8ta6v96uIvAAAA//8DAFBLAwQUAAYACAAAACEAgT6Ul/MAAAC6AgAAGgAIAXhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArFJNS8QwEL0L/ocwd5t2FRHZdC8i7FXrDwjJtCnbJiEzfvTfGyq6XVjWSy8Db4Z5783Hdvc1DuIDE/XBK6iKEgR6E2zvOwVvzfPNAwhi7a0egkcFExLs6uur7QsOmnMTuT6SyCyeFDjm+CglGYejpiJE9LnShjRqzjB1Mmpz0B3KTVney7TkgPqEU+ytgrS3tyCaKWbl/7lD2/YGn4J5H9HzGQlJPA15ANHo1CEr+MFF9gjyvPxmTXnOa8Gj+gzlHKtLHqo1PXyGdCCHyEcffymSc+WimbtV7+F0QvvKKb/b8izL9O9m5MnH1d8AAAD//wMAUEsDBBQABgAIAAAAIQDksKEbRAIAADcEAAAYAAAAeGwvd29ya3NoZWV0cy9zaGVldDEueG1snJLJTsMwFEX3SPyD5X3jJC0VjZoiAUJ0h5j2rvPSWPUQbHcS4t95TukgdVMRJY5jO+e+a9/x3UYrsgLnpTUlzZKUEjDCVtLMS/rx/tS7pcQHbiqurIGSbsHTu8n11Xht3cI3AIEgwfiSNiG0BWNeNKC5T2wLBmdq6zQP+OnmzLcOeNX9pBXL03TINJeG7giFu4Rh61oKeLRiqcGEHcSB4gHr941s/Z6mxSU4zd1i2faE1S0iZlLJsO2glGhRTOfGOj5T6HuTDbggG4d3jk9/L9ONnylpKZz1tg4Jktmu5nP7IzZiXBxI5/4vwmQD5mAl4wEeUfn/SspuDqz8COv/EzY8wOJ2uWIpq5J+p39XD99ZbNJjs5/7oZNxJfGEoyvioC7pfU7ZZNyF51PC2p/0SeCzN1AgAqBARknM5szaRVw4xaEUcb5bEHFcBLmCB1AKqViZ/9oJ9KMAOyic9vdqT12aXxypoOZLFV7t+hnkvAkoO0gG6DLGpKi2j+AF5hOlk4j9BQAA//8AAAD//7IpzkhNLXFJLEm0synKL1coslUyUlIoLkjMKwayrIDsCkOTxGSrlEqX1OLk1LwSWyUDPWMlO5tkkFInkFpbJUMlBaB4MVC0zM7ARr/MzkY/GYiB5gFJhAUAAAAA//8AAAD//7IpSExP9U0sSs/MK1bISU0rsVUy0DNXUijKTM+AsUvyC8CipkoKSfklJfm5MF5GamJKahGIZ6ykkJafXwLj6NvZ6JfnF2UXZ6SmltgBAAAA//8DAFBLAwQUAAYACAAAACEAdT6ZaZMGAACMGgAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWVuL20YUfi/0Pwi9O75Jsr3EG2zZTtrsJiHrpORxbI+tyY40RjPejQmBkjz1pVBIS18KfetDKQ000NCX/piFhDb9ET0zkq2Z9Tiby6a0JWtYpNF3znxzztE3F128dC+mzhFOOWFJ261eqLgOTsZsQpJZ2701HJSarsMFSiaIsgS33SXm7qXdjz+6iHZEhGPsgH3Cd1DbjYSY75TLfAzNiF9gc5zAsylLYyTgNp2VJyk6Br8xLdcqlaAcI5K4ToJicHt9OiVj7AylS3d35bxP4TYRXDaMaXogXWPDQmEnh1WJ4Ese0tQ5QrTtQj8TdjzE94TrUMQFPGi7FfXnlncvltFObkTFFlvNbqD+crvcYHJYU32ms9G6U8/zvaCz9q8AVGzi+o1+0A/W/hQAjccw0oyL7tPvtro9P8dqoOzS4rvX6NWrBl7zX9/g3PHlz8ArUObf28APBiFE0cArUIb3LTFp1ELPwCtQhg828I1Kp+c1DLwCRZQkhxvoih/Uw9Vo15Apo1es8JbvDRq13HmBgmpYV5fsYsoSsa3WYnSXpQMASCBFgiSOWM7xFI2hikNEySglzh6ZRVB4c5QwDs2VWmVQqcN/+fPUlYoI2sFIs5a8gAnfaJJ8HD5OyVy03U/Bq6tBnj97dvLw6cnDX08ePTp5+HPet3Jl2F1ByUy3e/nDV39997nz5y/fv3z8ddb1aTzX8S9++uLFb7+/yj2MuAjF82+evHj65Pm3X/7x42OL906KRjp8SGLMnWv42LnJYhighT8epW9mMYwQMSxQBL4trvsiMoDXlojacF1shvB2CipjA15e3DW4HkTpQhBLz1ej2ADuM0a7LLUG4KrsS4vwcJHM7J2nCx13E6EjW98hSowE9xdzkFdicxlG2KB5g6JEoBlOsHDkM3aIsWV0dwgx4rpPxinjbCqcO8TpImINyZCMjEIqjK6QGPKytBGEVBux2b/tdBm1jbqHj0wkvBaIWsgPMTXCeBktBIptLocopnrA95CIbCQPlulYx/W5gEzPMGVOf4I5t9lcT2G8WtKvgsLY075Pl7GJTAU5tPncQ4zpyB47DCMUz62cSRLp2E/4IZQocm4wYYPvM/MNkfeQB5RsTfdtgo10ny0Et0BcdUpFgcgni9SSy8uYme/jkk4RVioD2m9IekySM/X9lLL7/4yy2zX6HDTd7vhd1LyTEus7deWUhm/D/QeVu4cWyQ0ML8vmzPVBuD8It/u/F+5t7/L5y3Wh0CDexVpdrdzjrQv3KaH0QCwp3uNq7c5hXpoMoFFtKtTOcr2Rm0dwmW8TDNwsRcrGSZn4jIjoIEJzWOBX1TZ0xnPXM+7MGYd1v2pWG2J8yrfaPSzifTbJ9qvVqtybZuLBkSjaK/66HfYaIkMHjWIPtnavdrUztVdeEZC2b0JC68wkUbeQaKwaIQuvIqFGdi4sWhYWTel+lapVFtehAGrrrMDCyYHlVtv1vewcALZUiOKJzFN2JLDKrkzOuWZ6WzCpXgGwilhVQJHpluS6dXhydFmpvUamDRJauZkktDKM0ATn1akfnJxnrltFSg16MhSrt6Gg0Wi+j1xLETmlDTTRlYImznHbDeo+nI2N0bztTmHfD5fxHGqHywUvojM4PBuLNHvh30ZZ5ikXPcSjLOBKdDI1iInAqUNJ3Hbl8NfVQBOlIYpbtQaC8K8l1wJZ+beRg6SbScbTKR4LPe1ai4x0dgsKn2mF9akyf3uwtGQLSPdBNDl2RnSR3kRQYn6jKgM4IRyOf6pZNCcEzjPXQlbU36mJKZdd/UBR1VDWjug8QvmMoot5Blciuqaj7tYx0O7yMUNAN0M4mskJ9p1n3bOnahk5TTSLOdNQFTlr2sX0/U3yGqtiEjVYZdKttg280LrWSuugUK2zxBmz7mtMCBq1ojODmmS8KcNSs/NWk9o5Lgi0SARb4raeI6yReNuZH+xOV62cIFbrSlX46sOH/m2Cje6CePTgFHhBBVephC8PKYJFX3aOnMkGvCL3RL5GhCtnkZK2e7/id7yw5oelStPvl7y6Vyk1/U691PH9erXvVyu9bu0BTCwiiqt+9tFlAAdRdJl/elHtG59f4tVZ24Uxi8tMfV4pK+Lq80u1tv3zi0NAdO4HtUGr3uoGpVa9Myh5vW6z1AqDbqkXhI3eoBf6zdbggescKbDXqYde0G+WgmoYlrygIuk3W6WGV6t1vEan2fc6D/JlDIw8k488FhBexWv3bwAAAP//AwBQSwMEFAAGAAgAAAAhAB/6Qg7KAgAACgcAAA0AAAB4bC9zdHlsZXMueG1stFXbbtswDH0fsH8Q9O7KduMsCWwXS1MDBbZhQDtgr4otJ0J1MSQlczbs30fZTuKi3a3DXmKJog4PDykmvWqlQHtmLNcqw9FFiBFTpa642mT4030RzDCyjqqKCq1Yhg/M4qv89avUuoNgd1vGHAIIZTO8da5ZEGLLLZPUXuiGKTiptZHUwdZsiG0Mo5X1l6QgcRhOiaRc4R5hIcs/AZHUPOyaoNSyoY6vueDu0GFhJMvF7UZpQ9cCqLbRhJaojaYmRq05BumsT+JIXhptde0uAJfouuYle0p3TuaElmckQH4ZUpSQMH6Ue2teiDQhhu25Lx/O01orZ1Gpd8plOAaiXoLFg9JfVOGPoMKDV57ar2hPBVgiTPK01EIb5KB0oFxnUVSy3uOaCr423LvVVHJx6M2xN3TVHvwkB+29kXgePZs8XXuv/x6rC2khJhdipEBvyFNoFceMKuAUDev7QwOpKujqnjIc/dZ7Y+ghipPRBdIFhCy1qeAVHbX3MvemPBWsdqCB4Zut/zrdwO9aOwedlqcVpxutqPCyHW8MC0inZELc+Zf2uX6E3dZI7WQh3W2VYXizXvDjEhIZlj1ev/H4Y7QeewQbA+W/h0VtfcL/2e0I+D1P6nQb0aYRB9+jQ/d1XIHdSIJHApxSQb5PM/zBjxkBHT/QQesdF46rZ5IHzKo9yxn6ajo/MjqhT1FA1YrVdCfc/ekww+f1e1bxnYRHNnh95HvtOogMn9fvfNWjqY/BWvfOwrOAL9oZnuFvN8s389VNEQezcDkLJpcsCebJchUkk+vlalXMwzi8/j4aXP8wtro5CwWOJgsrYLiZIdmB/N3ZluHRpqff9TvQHnOfx9PwbRKFQXEZRsFkSmfBbHqZBEUSxavpZHmTFMmIe/LC8RaSKOoHpSefLByXTHB1rNWxQmMrFAm2v0iCHCtBzn9i+Q8AAAD//wMAUEsDBBQABgAIAAAAIQDZN1UFqwAAAMAAAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWw0jssKwjAQRfeC/xBmr6kuRCSNCx8gPkFduAztaAPNpHamon9vXLg8HC7nmvk71OqFLftIOYyGGSikIpaeHjlcL+vBFBSLo9LVkTCHDzLMbb9nmEWlLXEOlUgz05qLCoPjYWyQkrnHNjhJ2D40Ny26kitECbUeZ9lEB+cJVBE7ktQF1ZF/drj4szXsrRF7Op4van9Tu81hu1puDkaLNfrndHpgvwAAAP//AwBQSwMEFAAGAAgAAAAhAGAYt8dPAQAAbQIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHySX2uDMBTF3wf7DpJ3TdT+kaAWttGXrTCYY2NvIbltwzRKktX22y9q6xwde0zOub+cc0m6OlaldwBtZK0yFAYEeaB4LaTaZei1WPsJ8oxlSrCyVpChExi0ym9vUt5QXmt41nUD2kowniMpQ3mTob21DcXY8D1UzATOoZy4rXXFrDvqHW4Y/2Q7wBEhC1yBZYJZhjug34xEdEYKPiKbL132AMExlFCBsgaHQYh/vBZ0Zf4c6JWJs5L21LhO57hTtuCDOLqPRo7Gtm2DNu5juPwhft88vfRVfam6XXFAeSo45RqYrXX+COVBKq9wW9SyTvFE6tZYMmM3buNbCeLudOW+djh2X2V4AITnwtGhykV5i+8fijXKIxLOfbLwybwIExouaUQ+ugC/5ruww0V1jvEvMZr5JPHJsghnNE5oHE+IF0Ce4qsPkn8DAAD//wMAUEsDBBQABgAIAAAAIQBhSQkQiQEAABEDAAAQAAgBZG9jUHJvcHMvYXBwLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJySQW/bMAyF7wP6HwzdGzndUAyBrGJIV/SwYQGStmdNpmOhsiSIrJHs14+20dTZeuqN5Ht4+kRJ3Rw6X/SQ0cVQieWiFAUEG2sX9pV42N1dfhUFkgm18TFAJY6A4kZffFKbHBNkcoAFRwSsREuUVlKibaEzuGA5sNLE3BniNu9lbBpn4Tbalw4CyauyvJZwIAg11JfpFCimxFVPHw2tox348HF3TAys1beUvLOG+Jb6p7M5Ymyo+H6w4JWci4rptmBfsqOjLpWct2prjYc1B+vGeAQl3wbqHsywtI1xGbXqadWDpZgLdH94bVei+G0QBpxK9CY7E4ixBtvUjLVPSFk/xfyMLQChkmyYhmM5985r90UvRwMX58YhYAJh4Rxx58gD/mo2JtM7xMs58cgw8U4424FvOnPON16ZT/onex27ZMKRhVP1w4VnfEi7eGsIXtd5PlTb1mSo+QVO6z4N1D1vMvshZN2asIf61fO/MDz+4/TD9fJ6UX4u+V1nMyXf/rL+CwAA//8DAFBLAQItABQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhALVVMCP0AAAATAIAAAsAAAAAAAAAAAAAAAAAlwMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAObwxc7eAgAAtwYAAA8AAAAAAAAAAAAAAAAAvAYAAHhsL3dvcmtib29rLnhtbFBLAQItABQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAAAAAAAAAAAAAAAAMcJAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAIAAAAIQDksKEbRAIAADcEAAAYAAAAAAAAAAAAAAAAAPoLAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAYACAAAACEAdT6ZaZMGAACMGgAAEwAAAAAAAAAAAAAAAAB0DgAAeGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQAf+kIOygIAAAoHAAANAAAAAAAAAAAAAAAAADgVAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhANk3VQWrAAAAwAAAABQAAAAAAAAAAAAAAAAALRgAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAGAYt8dPAQAAbQIAABEAAAAAAAAAAAAAAAAAChkAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAGFJCRCJAQAAEQMAABAAAAAAAAAAAAAAAAAAkBsAAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAAoACgCAAgAATx4AAAAA";
        final String uriString = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).getPath() + "/algokelvinexcel" + "/" + noFile + "_" + fileName + ".xlsx";
        byte[] excelBytes = Base64.decode(base64Excel, Base64.DEFAULT);

        try {
            FileOutputStream os = new FileOutputStream(uriString);
            os.write(excelBytes);
            os.flush();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            // Open Excel file
            File fileExcel = new File(uriString);
            if (fileExcel.exists()) {
                Uri fileUri = FileProvider.getUriForFile(this, getApplicationContext().getPackageName() + ".provider", fileExcel);
                //Intent intent = new Intent(Intent.ACTION_VIEW);
                Intent intent = new Intent(Intent.ACTION_VIEW);
                intent.setDataAndType(fileUri, "application/vnd.ms-excel");
                intent.setFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
                intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                //startActivity(intent);

                // Check if there is an app that can open this type of file
//                 intent.resolveActivity(getPackageManager());
                if (intent.resolveActivity(getPackageManager()) != null) {
                    startActivity(intent);
                    //startActivityForResult(intent, REQUEST_OPEN_EXCEL); // Use startActivityForResult to get result back
                } else {
                    // No app found to open Excel file
                    Toast.makeText(this, "No application found to open this file", Toast.LENGTH_SHORT).show();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void viewFilePpt() {

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }
}