package com.algokelvin.performancedatascroll;

import java.util.ArrayList;
import java.util.List;

public class DummyItems {
    public static List<KamenRider> getListData10() {
        List<KamenRider> list = new ArrayList<>();

        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));

        return list;
    }

    public static List<KamenRider> getListData25() {
        List<KamenRider> list = new ArrayList<>();

        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));

        return list;
    }

    public static List<KamenRider> getListData50() {
        List<KamenRider> list = new ArrayList<>();

        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("40", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("41", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("42", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("43", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("44", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("45", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("46", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("47", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("48", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("49", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("50", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));

        return list;
    }

    public static List<KamenRider> getListData100() {
        List<KamenRider> list = new ArrayList<>();

        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("40", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("41", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("42", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("43", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("44", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("45", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("46", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("47", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("48", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("49", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("50", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("90", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("91", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("92", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("93", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("94", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("95", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("96", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("97", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("98", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("99", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("100", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));


        return list;
    }

    public static List<KamenRider> getListData200() {
        List<KamenRider> list = new ArrayList<>();

        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("40", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("41", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("42", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("43", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("44", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("45", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("46", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("47", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("48", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("49", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("50", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("90", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("91", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("92", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("93", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("94", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("95", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("96", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("97", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("98", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("99", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("100", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("40", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("41", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("42", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("43", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("44", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("45", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("46", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("47", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("48", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("49", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("50", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("15", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("16", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("17", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("18", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("19", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("20", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("21", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("22", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("23", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("24", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("25", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("01", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("02", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("03", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("04", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("05", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("06", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("07", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("08", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("09", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("10", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("11", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("12", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("13", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("14", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("190", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("191", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("192", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("193", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("194", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("195", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("196", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("197", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("198", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("199", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));
        list.add(new KamenRider("200", R.drawable.sample_img_card, "142", "Kuuga", "Rising", "", "Ultimate", "2000", "Godai Yusuke", "Joe Odagiri"));

        return list;
    }
}
